# Generated by Django 5.0.6 on 2024-06-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0002_alter_musicianmodel_phone_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicianModel',
            new_name='Musician',
        ),
    ]
