# Generated by Django 5.0.6 on 2024-06-26 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_rename_albummodel_album'),
        ('Musician', '0004_alter_musician_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Musician.musician'),
        ),
    ]
